# Generated by Django 5.1.4 on 2024-12-26 14:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0010_like'),
        ('userauth', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='user_post',
        ),
        migrations.AddField(
            model_name='profile',
            name='user_post',
            field=models.ManyToManyField(to='post.post'),
        ),
    ]
