# Generated by Django 5.1.4 on 2024-12-26 14:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('userauth', '0002_remove_profile_user_post_profile_user_post'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='user_post',
            new_name='favourite',
        ),
    ]
