# Generated by Django 5.1.4 on 2024-12-26 14:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('userauth', '0003_rename_user_post_profile_favourite'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='favourite',
            new_name='saved',
        ),
    ]
