# Generated by Django 5.1.4 on 2024-12-26 15:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0010_like'),
        ('userauth', '0004_rename_favourite_profile_saved'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='saved',
            field=models.ManyToManyField(blank=True, to='post.post'),
        ),
    ]
