# Generated by Django 5.1.4 on 2025-01-02 07:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('userauth', '0005_alter_profile_saved'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='saved',
        ),
    ]
