# Generated by Django 5.1.4 on 2025-01-02 15:58

import userauth.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userauth', '0006_remove_profile_saved'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=userauth.models.user_derectory_path),
        ),
    ]
