# Generated by Django 5.1.4 on 2024-12-25 20:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0004_alter_tag_options'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='tag',
            new_name='tags',
        ),
    ]
